server:
  port: 9090

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/security-demo
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password

